/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpio_horsent_lib_GPIOController */

#ifndef _Included_gpio_horsent_lib_GPIOController
#define _Included_gpio_horsent_lib_GPIOController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpio_horsent_lib_GPIOController
 * Method:    setGpioState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gpio_horsent_lib_GPIOController_setGpioState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     gpio_horsent_lib_GPIOController
 * Method:    getGpioState
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gpio_horsent_lib_GPIOController_getGpioState
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
